[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push", "npx tsx prisma/seed.ts", "npm run build"]

[start]
cmd = "npm start"