[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
port = 3001

[[services.domains]]
domain = "tarot-app-production-3381.up.railway.app"

[services.cors]
enabled = true
origins = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
headers = ["Content-Type", "Authorization", "X-Requested-With"]
credentials = true